force-app/main/default/objects/School__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Computer_Lab__c.field-meta.xml
<CustomField>
    <fullName>Computer_Lab__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Computer Lab</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Staff_Strength__c.field-meta.xml
<CustomField>
    <fullName>Staff_Strength__c</fullName>
    <label>Staff Strength</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/School__c/fields/Uniform_Color__c.field-meta.xml
<CustomField>
    <fullName>Uniform_Color__c</fullName>
    <label>Uniform Color</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Khaki</fullName>
            </value>
            <value>
                <fullName>Wine</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SchoolInformation.cls
public with sharing class SchoolInformation{

    public static School__c getSchoolByName (String schName){
        School__c sch = [SELECT Id, Name, Class__c, Fee__c, Uniform_Color__c, Computer_Lab__c, Staff_Strength__c, Email__c, Phone_No__c FROM School__c WHERE Name =: schName];
        return sch;
    }
    
    public static List<School__c> getSchoolByUniColor(String uniColor){
        List<School__c> schoolList = [SELECT Id, Name, Class__c, Fee__c, Uniform_Color__c, Computer_Lab__c, Staff_Strength__c, Email__c, Phone_No__c FROM School__c WHERE  Uniform_Color__c INCLUDES (:uniColor)];
        return schoolList;
    }



}